# Site settings
title: Shaun Hills
description: > # this means to ignore newlines until "baseurl:"
  The personal site of Shaun Hills
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hillsy.org" # the base hostname & protocol for your site
twitter_username: hillsy
github_username:  hillsy

# Build settings
markdown: kramdown
